### ISSUE TITLE
Add other options for box spread

### ISSUE THREAD

**Issue by andrewcz** [asemx/ibkrbox#2]
amazing package @asemx !!

If i wanted to add other options to try for a box spread how would i do this?
Best,
Andrew

**Comment by asemx** [comment]
can you specify what you are looking for, we can add them. you are free to push PR as well.

**Comment by andrewcz** [comment]
I have a rough pr.
I was looking at the below options.
https://www.eurex.com/ex-en/markets/idx/country/six/SMI-Options-10212

**Comment by andrewcz** [comment]
I think there is an issue with the pull for the treasury rates @asemx  - (test_env_box) C:\Users\andrewcz>ibkrbox -a 50000 -m 4 --short
SPX last close: 5521.56
Traceback (most recent call last):
  File "C:\Users\andrewcz\miniconda3\envs\test_env_box\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\andrewcz\miniconda3\envs\test_env_box\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\andrewcz\miniconda3\envs\test_env_box\Scripts\ibkrbox.exe\__main__.py", line 7, in <module>
  File "C:\Users\andrewcz\miniconda3\envs\test_env_box\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\andrewcz\miniconda3\envs\test_env_box\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\andrewcz\miniconda3\envs\test_env_box\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\andrewcz\miniconda3\envs\test_env_box\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\andrewcz\miniconda3\envs\test_env_box\lib\site-packages\ibkrbox\cli.py", line 67, in cli
    rate = get_rate(expiry) + 0.30
  File "C:\Users\andrewcz\miniconda3\envs\test_env_box\lib\site-packages\ibkrbox\ibkrbox.py", line 139, in get_rate
    assert list(rates_.columns)[1:11] == [
AssertionError: problem with treasury rates site, pass rate or limit price manually

(test_env_box) C:\Users\andrewcz>
